import type { Metadata } from "next";
import { Noto_Serif_Bengali } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";
import CategoryItem from "./components/CategoryItem";
import Marquee from "@/app/components/Marquee";
import { ToastContainer } from "react-toastify";

const NotoSerifBengali = Noto_Serif_Bengali({
  subsets: ["latin", "bengali"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${NotoSerifBengali.className} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col bg-[#f1f5f0]">
        <div className="sticky top-0 z-50">
          <Navbar />
          <CategoryItem />
        </div>
        <Marquee />
        <main>
          {children}
          <ToastContainer />
        </main>
        <Footer />
      </body>
    </html>
  );
}
