import type { Metadata } from "next";
import { Noto_Serif_Bengali } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";
import CategoryItem from "./components/CategoryItem";
import Marquee from "@/app/components/Marquee";

const NotoSerifBengali = Noto_Serif_Bengali({
  subsets: ["latin",'bengali'],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${NotoSerifBengali.className} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <Navbar/>
        <CategoryItem/>
        <Marquee/>
        <main>{children}</main>
        <Footer/>
      </body>
    </html>
  );
}
